server:
  port: 8762
  
spring:
  application:
    name: service1
  datasource:
    url: jdbc:mysql://203.2.161.184:3306/mxz
    username: mxz
    password: qq741852
    driver-class-name:  com.mysql.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop #是否自动建库 默认为none 
    show-sql: true
      
    
  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册的EurekaServer地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  注册到其他上面
  instance:
    metadata-map:
      zone: ${COMPUTERNAME}#匹配调用
    prefer-ip-address: true
info:
  author: XXX
  build-version: $project.version$
  
