server:
  port: 8764
  
spring:
  application:
    name: service-ribbon
  #Sleuth 配置
  zipkin:
    base-url: http://localhost:9411
    
    
  devtools:
    restart:
      enabled: true #如果不想使用重启功能，可以使用spring.devtools.restart.enabled属性来禁用它
      additional-paths: -src/main/java
    #与LiveReload一起使用时，自动重启的效果非常好  
    livereload:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册的EurekaServer地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  注册到其他上面
    register-with-eureka: false        #作为消费者不提供服务，不应该注册自己
    
  instance:
    metadata-map:
      zone: ${COMPUTERNAME}#匹配调用
    prefer-ip-address: true
info:
  author: XXX
  build-version: $project.version$
#如果不想使用重启功能，可以使用spring.devtools.restart.enabled属性来禁用它