server:
  port: 8763
  
spring:
  application:
    name: s2

#  公共配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册的EurekaServer地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  注册到其他上面
  instance:
    metadata-map:
      zone: ${COMPUTERNAME}#匹配调用
    prefer-ip-address: true
info:
  author: mxz
  build-version: $project.version$