server:
  port: 8769
  
spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册的EurekaServer地址
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  注册到其他上面
  instance:
    metadata-map:
      zone: ${COMPUTERNAME}#匹配调用
    prefer-ip-address: true
info:
  author: XXX
  build-version: $project.version$
  
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service1
    api-b:
      path: /api-b/**
      serviceId: service2
    #service2: /api-b/**也可这样配
