foo:
  tt
spring:
  datasource:
    url: jdbc:mysql://203.2.161.184:3306/mxz?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver